<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <UserSecretsId>figet-web</UserSecretsId>
    <InvariantGlobalization>true</InvariantGlobalization>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\FiGet.Core\FiGet.Core.csproj" />
    <ProjectReference Include="..\FiGet.Persistence\FiGet.Persistence.csproj" />
    <ProjectReference Include="..\FiGet.Persistence.SqlServer\FiGet.Persistence.SqlServer.csproj" />
    <ProjectReference Include="..\FiGet.Persistence.Sqlite\FiGet.Persistence.Sqlite.csproj" />
    <ProjectReference Include="..\FiGet.Storage\FiGet.Storage.csproj" />
    <ProjectReference Include="..\FiGet.Http\FiGet.Http.csproj" />
    <ProjectReference Include="..\FiGet.Protocol.V3\FiGet.Protocol.V3.csproj" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="FiGet.Integration.Tests" />
  </ItemGroup>
</Project>
