<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <NoWarn>$(NoWarn);CA1707;CA2201;CA1861;xUnit1051</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\FiGet.Core\FiGet.Core.csproj" />
    <ProjectReference Include="..\..\src\FiGet.Storage\FiGet.Storage.csproj" />
    <ProjectReference Include="..\FiGet.Testing\FiGet.Testing.csproj" />
  </ItemGroup>
</Project>
